base_url = "https://www.mkemorgn.com"
default_language = "en"
highlight_code = true
highlight_theme = "one-dark"
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
	{ name = "categories", feed = true, paginate_by = 10 },
	{ name = "tags", fees = true, paginate_by = 10 },
]
languages = []
compile_sass = true
build_search_index = true
ignored_content = []
extra_syntaxes = []

[link_checker]
skip_prefixes = ["http://[2001:db8::]/"]
skip_anchor_prefixes = ["https://caniuse.com/"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[translations]

[extra]
navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/photos", name = "Photos" },
  { url = "$BASE_URL/code", name = "Code" },
 ]}
]

[extra.favicon]
favicon_16x16 = ""
favicon_32x32 = ""
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "Mike Morgan"
avatar = "/images/me1.jpg"

[extra.social]
github = "mkemorgn"
email = "morgan.mike55@gmail.com"
twitter = "mkemorgn"
instagram = "mkemorgn"

[extra.commenting]
hyvor = "1967"
