version: '3.8'

services:
  pg:
    image: postgres:14.2-alpine
    container_name: mkemorgn
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 150557
    ports:
      - '15432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
